version: '3.3'
services:
  feishu-chatgpt:
    container_name: feishu-chatgpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000/tcp"
    # volumes:
    #   - ./code/config.yaml:/app/config.yaml:ro
    environment:
      - APP_ID=cli_a4f6f1488721500e
      - APP_SECRET=PKpyW1x0IVtuNPKi38UDwhJoRZyDQEVO
      - APP_ENCRYPT_KEY=Uq6ZRLRJmNX3ZwMWn6w91cwce1bvU5Ed
      - APP_VERIFICATION_TOKEN=TvaQr2fVnhjjXfNIDwseIh14SlaJOV0A
      # 请确保和飞书应用管理平台中的设置一致
      - BOT_NAME=GPT4
      # OpenAI API Key 支持负载均衡, 可以填写多个 Key 用逗号分隔
      - OPENAI_KEY=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
      # 服务器配置
      - HTTP_PORT=9000
      - HTTPS_PORT=9001
      - USE_HTTPS=false
      - CERT_FILE=cert.pem
      - KEY_FILE=key.pem
      # OpenAI 地址, 一般不需要修改, 除非你有自己的反向代理
      - API_URL=https://api.openai.com
      # 代理设置, 例如 - HTTP_PROXY=http://127.0.0.1:7890, 默认代表不使用代理
      - HTTP_PROXY
